export declare const DEFAULT_CORNER_RADIUS = 16;
export declare const DEFAULT_MAX_WIDTH = 640;
export declare const DEFAULT_FORM_SHEET_WIDTH = 580;
export declare const DEFAULT_FORM_SHEET_HEIGHT_RATIO = 0.5;
export declare const COLOR_SURFACE_CONTAINER_LOW_LIGHT = "#F7F2FA";
export declare const COLOR_SURFACE_CONTAINER_LOW_DARK = "#1D1B20";
export declare const DEFAULT_ANCHOR_OFFSET = 16;
export declare const DEFAULT_DETACHED_OFFSET = 16;
export declare const DEFAULT_GRABBER_COLOR_LIGHT = "rgba(0, 0, 0, 0.3)";
export declare const DEFAULT_GRABBER_COLOR_DARK = "rgba(255, 255, 255, 0.3)";
export declare const DEFAULT_GRABBER_WIDTH = 32;
export declare const DEFAULT_GRABBER_HEIGHT = 4;
export declare const DEFAULT_GRABBER_TOP_MARGIN = 8;
//# sourceMappingURL=constants.d.ts.map